/* KB — people, animals, creatures.
 * person fields: g (f|m|n|p), gen (generic human, not a role), grp (group noun),
 *   wear (string | {f,m,n}), look [NP], gear (prop NP), hab ('place:w, ...')
 * animal fields: look [NP], coat (fur|feathers|scales|skin|plating), hab
 */
(function () {
  const SC = globalThis.SC;

  SC.def('person', {
    woman: { syn: 'lady|female|gal|women|ladies', g: 'f', gen: 1 },
    man: { syn: 'guy|gentleman|male|dude|bloke|fellow|lad|gentlemen', g: 'm', gen: 1 },
    girl: { syn: 'little girl|young girl|daughter', g: 'f', gen: 1, age: 'child' },
    boy: { syn: 'little boy|young boy|son', g: 'm', gen: 1, age: 'child' },
    child: { syn: 'kid|toddler|youngster|children|kids', g: 'n', gen: 1, age: 'child', pl: 'children' },
    baby: { syn: 'infant|newborn', g: 'n', gen: 1, age: 'baby', bias: { shot: 'close-up:2' } },
    teenager: { syn: 'teen|adolescent|teens', g: 'n', gen: 1, age: 'teen' },
    person: { syn: 'someone|human|individual|figure|stranger|silhouette figure', g: 'n', gen: 1, pl: 'people' },
    'old man': { syn: 'elderly man|grandfather|grandpa|old guy|old gentleman|senior man|aged man', g: 'm', gen: 1, look: ['deeply lined, weathered skin'] },
    'old woman': { syn: 'elderly woman|grandmother|grandma|granny|old lady|senior woman|aged woman', g: 'f', gen: 1, look: ['silver hair and softly wrinkled skin'] },
    mother: { syn: 'mom|mum|mama|mommy', g: 'f', gen: 1 },
    father: { syn: 'dad|papa|daddy', g: 'm', gen: 1 },
    couple: { syn: 'lovers|young couple|pair of lovers', g: 'p', gen: 1, grp: 1, tags: 'romance' },
    family: { syn: 'families', g: 'p', gen: 1, grp: 1 },
    crowd: { syn: 'throng|mass of people|crowds', g: 'p', gen: 1, grp: 1, bias: { shot: 'wide shot:3' } },
    friends: { syn: 'group of friends|best friends|friend group', n: 'group of friends', pl: 'groups of friends', g: 'p', gen: 1, grp: 1 },

    astronaut: { syn: 'spaceman|cosmonaut|spacewoman|astronauts', wear: 'a white pressurized spacesuit with a reflective gold-tinted visor', look: ['mission patches and scuffed fabric on the suit'], hab: 'outer space:3, moon surface:2', tags: 'scifi space' },
    samurai: { wear: 'layered lacquered armor over a dark hakama, twin swords at the hip', hab: 'bamboo forest:2, temple:1', tags: 'japan historic warrior', g: 'm' },
    ninja: { wear: 'close-fitting black shinobi garb with a face wrap', hab: 'rooftop:2, bamboo forest:1', tags: 'japan stealth' },
    knight: { wear: 'battle-worn plate armor over chainmail and a torn heraldic surcoat', hab: 'castle:2, battlefield:2', tags: 'medieval warrior', g: 'm' },
    warrior: { syn: 'fighter|swordsman|swordswoman', wear: 'battle-scarred leather armor with bronze fittings', tags: 'warrior' },
    soldier: { syn: 'trooper|infantryman|marine', wear: 'mud-streaked combat fatigues, a tactical vest and helmet', hab: 'battlefield:2', tags: 'military' },
    pirate: { syn: 'buccaneer|captain', wear: 'a weathered long coat, loose linen shirt and a tricorn hat', hab: 'pirate ship:2, beach:1', tags: 'nautical historic' },
    cowboy: { syn: 'cowgirl|gunslinger|rancher|outlaw', wear: 'a dusty duster coat, leather chaps and a wide-brimmed hat', hab: 'desert:2', tags: 'western' },
    detective: { syn: 'investigator|private eye|sleuth|inspector', wear: 'a belted trench coat and a fedora', hab: 'alley:2', tags: 'noir', bias: { time: 'night:2' } },
    wizard: { syn: 'mage|sorcerer|warlock|magician', g: 'm', wear: 'flowing star-embroidered robes', gear: 'a gnarled wooden staff', tags: 'fantasy magic' },
    witch: { syn: 'sorceress|enchantress', g: 'f', wear: 'layered dark robes and a wide pointed hat', tags: 'fantasy magic' },
    king: { syn: 'emperor|monarch|sultan|maharaja|raja', g: 'm', wear: 'rich velvet robes trimmed with ermine and a jeweled crown', hab: 'throne room:3, palace:2', tags: 'royal' },
    queen: { syn: 'empress|maharani|rani', g: 'f', wear: 'an embroidered silk gown and a jeweled crown', hab: 'throne room:3, palace:2', tags: 'royal' },
    princess: { g: 'f', wear: 'a flowing gown with delicate embroidery and a slim tiara', hab: 'palace:2', tags: 'royal fairytale' },
    prince: { g: 'm', wear: 'a tailored brocade coat with gold buttons', hab: 'palace:2', tags: 'royal' },
    monk: { syn: 'buddhist monk|lama|monks', g: 'm', wear: 'simple saffron robes', hab: 'monastery:3, temple:2', tags: 'sacred calm' },
    priest: { syn: 'pastor|vicar|pujari|pandit', g: 'm', wear: 'plain ceremonial robes', hab: 'cathedral:2, temple:2', tags: 'sacred' },
    nun: { g: 'f', wear: 'a black-and-white habit', hab: 'cathedral:2', tags: 'sacred' },
    sadhu: { syn: 'holy man|ascetic|yogi|sage|rishi|baba', g: 'm', wear: 'saffron cloth draped loosely with strings of rudraksha beads', look: ['long matted locks, ash-smeared skin and a vermilion tilak on the forehead'], hab: 'ghat:3, temple:2', tags: 'india sacred' },
    chef: { syn: 'cook|head chef', wear: "a crisp white chef's jacket and apron", hab: 'kitchen:3', tags: 'food' },
    doctor: { syn: 'surgeon|physician', wear: 'a white coat over blue scrubs with a stethoscope', hab: 'hospital:3' },
    nurse: { wear: 'clean pale-blue scrubs', hab: 'hospital:3' },
    scientist: { syn: 'researcher|chemist|professor|engineer', wear: 'a white lab coat and safety glasses', hab: 'laboratory:3', tags: 'tech' },
    teacher: { syn: 'tutor|lecturer', wear: 'a neat cardigan over a pressed shirt', hab: 'classroom:3' },
    student: { syn: 'schoolgirl|schoolboy|pupil|college student', wear: 'a school uniform with a backpack slung over one shoulder', hab: 'classroom:2, library:2' },
    farmer: { syn: 'villager|peasant|kisan', wear: 'sun-faded work clothes and a wide straw hat', hab: 'farm:3, field:2', tags: 'rural' },
    fisherman: { syn: 'fisher|fishermen', g: 'm', wear: 'salt-stained work clothes with rolled-up sleeves', hab: 'harbor:3, beach:2', tags: 'nautical' },
    shepherd: { syn: 'herder|goatherd', wear: 'a heavy wool cloak', gear: 'a wooden crook', hab: 'meadow:2, mountain:1', tags: 'rural' },
    dancer: { syn: 'dancers', wear: 'flowing performance clothes that trail with every movement', hab: 'stage:2', tags: 'dance' },
    ballerina: { syn: 'ballet dancer', g: 'f', wear: 'a pale tulle tutu and satin pointe shoes', hab: 'stage:3', tags: 'dance elegant' },
    'kathakali dancer': { syn: 'kathakali|kathakali performer', g: 'n', wear: 'a voluminous white pleated skirt, layered jewelry and a towering gilded crown', look: ['vivid green face paint framed by a white chutti ridge', 'reddened, intensely expressive eyes'], hab: 'temple:3, stage:2', tags: 'india dance' },
    'classical dancer': { syn: 'bharatanatyam dancer|kathak dancer|odissi dancer', g: 'f', wear: 'a pleated silk costume with temple jewelry and ankle bells', look: ['kohl-lined eyes and hennaed hands'], hab: 'temple:2, stage:2', tags: 'india dance' },
    musician: { syn: 'band|musicians', wear: 'relaxed stage clothes', hab: 'stage:2', tags: 'music' },
    guitarist: { wear: 'a worn denim jacket', gear: 'an electric guitar', hab: 'stage:2', tags: 'music' },
    singer: { syn: 'vocalist|rockstar|rock star|pop star', wear: 'a sequined stage outfit', hab: 'stage:3', tags: 'music' },
    dj: { n: 'DJ', wear: 'headphones around the neck and a black tee', hab: 'nightclub:4', tags: 'music party' },
    painter: { syn: 'artist', wear: 'a paint-spattered smock', hab: 'art studio:3', tags: 'art' },
    photographer: { wear: 'a utility jacket with a camera strap across the chest', gear: 'a camera', tags: 'art' },
    businessman: { syn: 'executive|ceo|entrepreneur|banker|office worker', g: 'm', wear: 'a sharply tailored charcoal suit', hab: 'office:3, city:1', tags: 'corporate' },
    businesswoman: { syn: 'female executive', g: 'f', wear: 'a tailored blazer and wide-leg trousers', hab: 'office:3, city:1', tags: 'corporate' },
    athlete: { syn: 'sportsman|sportswoman', wear: 'performance athletic wear', hab: 'stadium:3', tags: 'sport' },
    runner: { syn: 'jogger|sprinter|marathoner', wear: 'lightweight running gear and trail shoes', hab: 'park:1, road:1', tags: 'sport' },
    boxer: { syn: 'mma fighter|prizefighter|wrestler', wear: 'boxing trunks and taped hands in red gloves', hab: 'boxing ring:4, gym:2', tags: 'sport gritty' },
    cricketer: { syn: 'batsman|batter|bowler|cricket player', wear: 'cricket whites and pads', hab: 'stadium:2, field:2', tags: 'sport india' },
    footballer: { syn: 'soccer player|football player', wear: 'a mud-flecked football kit', hab: 'stadium:3', tags: 'sport' },
    cyclist: { syn: 'bicyclist', wear: 'a fitted cycling jersey and helmet', tags: 'sport' },
    skateboarder: { syn: 'skater', wear: 'baggy streetwear and scuffed sneakers', hab: 'skatepark:3, street:1', tags: 'sport street' },
    surfer: { wear: 'a black wetsuit', gear: 'a surfboard', hab: 'ocean:3, beach:2', tags: 'sport water' },
    climber: { syn: 'mountaineer|rock climber|alpinist', wear: 'a technical shell jacket, harness and helmet', hab: 'mountain:3, cliff:2', tags: 'adventure' },
    hiker: { syn: 'backpacker|trekker', wear: 'layered hiking gear and a loaded backpack', hab: 'mountain:2, forest:2', tags: 'adventure' },
    traveler: { syn: 'traveller|tourist|wanderer|nomad|drifter|voyager', wear: 'a well-worn travel jacket and a canvas backpack', tags: 'adventure' },
    explorer: { syn: 'adventurer|archaeologist', wear: 'a sun-bleached field shirt, leather satchel and brimmed hat', hab: 'jungle:2, ruins:2, desert:1', tags: 'adventure' },
    pilot: { syn: 'aviator', wear: 'a leather flight jacket and aviator sunglasses', hab: 'airfield:2' },
    firefighter: { syn: 'fireman', wear: 'soot-streaked turnout gear and a helmet', tags: 'fire' },
    'police officer': { syn: 'policeman|policewoman|cop|officer|police', wear: 'a dark uniform with a reflective vest' },
    'street vendor': { syn: 'vendor|hawker|shopkeeper|merchant|seller', wear: 'a practical cotton shirt with a cloth tied at the waist', hab: 'market:3, street:2', tags: 'street' },
    'chai wala': { syn: 'chaiwala|chai seller|tea seller|chai vendor', g: 'm', wear: 'a faded cotton shirt with sleeves rolled up', gear: 'a dented aluminium kettle and small glass cups', hab: 'street:3, railway station:2', tags: 'india street' },
    'rickshaw driver': { syn: 'auto driver|rickshaw puller|rickshaw wala|cab driver|taxi driver', g: 'm', wear: 'a khaki uniform shirt', hab: 'street:3', tags: 'street' },
    waiter: { syn: 'waitress|server|bartender|barista', wear: 'a crisp white shirt and a black apron', hab: 'restaurant:2, cafe:2, bar:1' },
    mechanic: { syn: 'engineer mechanic', wear: 'grease-stained overalls', hab: 'garage:3', tags: 'gritty' },
    'construction worker': { syn: 'worker|laborer|labourer|builder', wear: 'a hi-vis vest and a scuffed hard hat', hab: 'construction site:3', tags: 'gritty' },
    bride: { g: 'f', wearIn: { india: 'a heavily embroidered red bridal lehenga with gold zari work', japan: 'a pure white shiromuku wedding kimono' }, wear: 'an ornate bridal gown with intricate embroidery and a sheer veil', look: ['delicate jewelry'], tags: 'wedding festive' },
    groom: { syn: 'bridegroom|dulha', g: 'm', wearIn: { india: 'an ivory silk sherwani with a jeweled safa turban', japan: 'a black montsuki kimono with a striped hakama' }, wear: 'a tailored wedding suit with a boutonniere', tags: 'wedding festive' },
    'indian bride': { syn: 'dulhan', g: 'f', wear: 'a heavily embroidered red bridal lehenga with gold zari work', look: ['layered gold jewelry, a maang tikka and intricate henna on her hands'], tags: 'wedding festive india' },
    model: { syn: 'fashion model|supermodel', wear: 'an avant-garde designer outfit', tags: 'fashion', bias: { style: 'fashion:3' } },
    hacker: { syn: 'coder|programmer|developer', wear: 'a dark hoodie lit by screen glow', hab: 'bedroom:1, server room:2', tags: 'tech' },
    gamer: { syn: 'streamer', wear: 'an oversized hoodie and a gaming headset', hab: 'bedroom:2', tags: 'tech' },
    cyborg: { syn: 'android|synthetic human|replicant', wear: 'minimal matte-black armor plating', look: ['seams where synthetic skin gives way to exposed chrome mechanics'], tags: 'scifi robot' },
    vampire: { wear: 'a high-collared black coat', look: ['pale porcelain skin and faintly glowing red eyes'], tags: 'horror gothic', bias: { time: 'night:4' } },
    zombie: { syn: 'undead|walker', wear: 'torn, filth-stained clothing', look: ['decaying grey skin and clouded eyes'], tags: 'horror' },
    ghost: { syn: 'spirit|apparition|phantom|specter|spectre', wear: 'a tattered, drifting white shroud', look: ['a translucent, faintly glowing form'], tags: 'horror supernatural' },
    elf: { syn: 'elven|elves', wear: 'finely woven green and silver garments', look: ['pointed ears and luminous eyes'], tags: 'fantasy' },
    fairy: { syn: 'pixie|faerie|sprite|fairies', g: 'f', wear: 'a gossamer dress of petals', look: ['delicate translucent dragonfly wings'], tags: 'fantasy magic small' },
    mermaid: { syn: 'merman|mermaids|siren', g: 'f', look: ['a shimmering scaled tail in aquamarine tones'], hab: 'underwater:3, ocean:2', tags: 'fantasy aquatic' },
    angel: { syn: 'angels|seraph', wear: 'flowing white robes', look: ['vast feathered wings'], tags: 'sacred fantasy' },
    demon: { syn: 'devil|demons|fiend', wear: 'scorched black armor', look: ['curling horns and ember-lit cracks across charred skin'], tags: 'horror fantasy' },
    superhero: { syn: 'hero|heroine|vigilante|superheroine', wear: 'a sleek armored suit with a flowing cape', tags: 'superhero', bias: { angle: 'low angle:3' } },
    clown: { syn: 'jester|harlequin', wear: 'a patched, oversized costume', look: ['smeared white face paint'], tags: 'circus' },
    geisha: { syn: 'maiko', g: 'f', wear: 'an elaborate silk kimono tied with a wide obi', look: ['white face makeup and crimson lips'], tags: 'japan elegant' },
    viking: { syn: 'norseman|shieldmaiden', wear: 'fur-trimmed leather and chainmail with a round wooden shield', hab: 'fjord:2', tags: 'historic nordic warrior' },
    gladiator: { wear: 'bronze armor pieces and a crested helmet', hab: 'colosseum:3', tags: 'historic warrior' },
    pharaoh: { wear: 'a striped nemes headdress and a broad golden collar', hab: 'temple:1, desert:1', tags: 'egypt historic royal' },
    tribesman: { syn: 'tribal warrior|tribeswoman|indigenous elder', wear: 'hand-woven textiles and beaded ornaments', tags: 'rural' },
    'mughal emperor': { syn: 'nawab|mughal prince', g: 'm', wear: 'a jewel-encrusted silk jama with a plumed turban', hab: 'palace:3', tags: 'india historic royal' },
  });

  SC.def('animal', {
    cat: { syn: 'kitty|feline|house cat|tabby|cats', coat: 'fur', look: ['soft striped fur and bright amber eyes'], hab: 'living room:1', tags: 'pet small' },
    kitten: { coat: 'fur', look: ['fluffy fur and oversized curious eyes'], tags: 'pet small cute' },
    dog: { syn: 'doggo|hound|canine|labrador|retriever|golden retriever|german shepherd|husky', coat: 'fur', look: ['a glossy coat and alert, expressive eyes'], hab: 'park:1', tags: 'pet' },
    puppy: { syn: 'pup|pupper', coat: 'fur', look: ['fluffy fur and oversized paws'], tags: 'pet small cute' },
    wolf: { coat: 'fur', look: ['a thick grey coat and piercing amber eyes'], hab: 'forest:2, tundra:1', tags: 'wild predator' },
    fox: { syn: 'red fox|arctic fox', coat: 'fur', look: ['russet fur and a white-tipped bushy tail'], hab: 'forest:2, meadow:1', tags: 'wild small' },
    lion: { syn: 'lioness', coat: 'fur', look: ['a thick golden mane framing a scarred, noble face'], hab: 'savanna:4', tags: 'wild predator big' },
    tiger: { syn: 'bengal tiger|tigress|white tiger', coat: 'fur', look: ['bold black stripes over burnt-orange fur'], hab: 'jungle:4', tags: 'wild predator big india' },
    leopard: { syn: 'panther|jaguar|black panther', coat: 'fur', look: ['rosette-spotted golden fur'], hab: 'jungle:2, savanna:2', tags: 'wild predator' },
    'snow leopard': { coat: 'fur', look: ['smoky grey fur patterned with dark rosettes and a long, thick tail'], hab: 'mountain:4', tags: 'wild predator cold' },
    cheetah: { coat: 'fur', look: ['a lean spotted body built for speed'], hab: 'savanna:4', tags: 'wild predator fast' },
    elephant: { syn: 'tusker|elephants', coat: 'skin', look: ['deeply wrinkled grey skin and long curving tusks'], hab: 'savanna:3, jungle:2', tags: 'wild big india' },
    horse: { syn: 'stallion|mare|pony|steed|horses', coat: 'coat', look: ['a glossy chestnut coat and a flowing mane'], hab: 'meadow:3', tags: 'domestic' },
    deer: { syn: 'stag|doe|fawn|reindeer|elk|moose|antelope|gazelle', coat: 'fur', look: ['a warm brown coat and branching antlers'], hab: 'forest:4', tags: 'wild shy' },
    bear: { syn: 'grizzly|brown bear|black bear|grizzly bear', coat: 'fur', look: ['a shaggy brown coat and massive shoulders'], hab: 'forest:3, river:2', tags: 'wild big predator' },
    'polar bear': { coat: 'fur', look: ['dense cream-white fur'], hab: 'arctic:5', tags: 'wild big cold' },
    panda: { syn: 'giant panda|red panda', coat: 'fur', look: ['black-and-white fur and a round, gentle face'], hab: 'bamboo forest:5', tags: 'wild cute' },
    rabbit: { syn: 'bunny|hare', coat: 'fur', look: ['soft fur and long twitching ears'], hab: 'meadow:3', tags: 'small cute' },
    squirrel: { syn: 'chipmunk', coat: 'fur', look: ['a bushy tail and bright, beady eyes'], hab: 'park:2, forest:2', tags: 'small wild' },
    hedgehog: { coat: 'spines', look: ['a coat of soft-tipped spines and a tiny snout'], hab: 'garden:2', tags: 'small cute', bias: { shot: 'macro:2' } },
    raccoon: { coat: 'fur', look: ['a bandit-masked face and ringed tail'], hab: 'alley:2, forest:1', tags: 'small wild' },
    otter: { syn: 'sea otter', coat: 'fur', look: ['sleek water-darkened fur and whiskered snout'], hab: 'river:4', tags: 'small cute aquatic' },
    owl: { syn: 'owls|barn owl|snowy owl', coat: 'feathers', look: ['mottled feathers and large luminous eyes'], hab: 'forest:3', tags: 'bird wild', bias: { time: 'night:2' } },
    eagle: { syn: 'bald eagle|golden eagle|eagles', coat: 'feathers', look: ['broad powerful wings and a hooked golden beak'], hab: 'mountain:3, sky:2', tags: 'bird wild predator' },
    hawk: { syn: 'falcon|kestrel', coat: 'feathers', look: ['sleek barred feathers and fierce eyes'], hab: 'sky:2', tags: 'bird wild predator' },
    crow: { syn: 'raven|crows|ravens', coat: 'feathers', look: ['glossy blue-black feathers'], tags: 'bird ominous' },
    parrot: { syn: 'macaw|cockatoo|parakeet', coat: 'feathers', look: ['brilliant scarlet, blue and yellow plumage'], hab: 'jungle:3', tags: 'bird tropical' },
    peacock: { syn: 'peafowl|peahen', coat: 'feathers', look: ['a fanned train of iridescent eye-spotted feathers'], hab: 'garden:2, palace:1', tags: 'bird india' },
    hummingbird: { coat: 'feathers', look: ['iridescent emerald feathers and wings blurred mid-beat'], hab: 'garden:3', tags: 'bird small', bias: { shot: 'macro:3' } },
    sparrow: { syn: 'songbird|robin|finch|bird|birds|pigeon|dove|doves|pigeons', coat: 'feathers', look: ['soft layered feathers and a bright eye'], tags: 'bird small' },
    penguin: { syn: 'penguins', coat: 'feathers', look: ['sleek black-and-white plumage'], hab: 'arctic:4', tags: 'bird cold' },
    flamingo: { syn: 'flamingos', coat: 'feathers', look: ['vivid pink plumage and slender legs'], hab: 'lake:3', tags: 'bird' },
    swan: { syn: 'swans|heron|crane bird', coat: 'feathers', look: ['pure white plumage and a gracefully curved neck'], hab: 'lake:4', tags: 'bird elegant' },
    butterfly: { syn: 'butterflies|moth', coat: 'wings', look: ['delicate patterned wings dusted with scales'], hab: 'garden:3, meadow:2', tags: 'insect small', bias: { shot: 'macro:4' } },
    bee: { syn: 'honeybee|bumblebee|bees', coat: 'fuzz', look: ['a fuzzy golden-black body dusted with pollen'], hab: 'garden:3', tags: 'insect small', bias: { shot: 'macro:5' } },
    dragonfly: { syn: 'damselfly', coat: 'wings', look: ['glassy veined wings and a metallic blue body'], hab: 'lake:2', tags: 'insect small', bias: { shot: 'macro:4' } },
    spider: { syn: 'tarantula|spiders', coat: 'hair', look: ['long jointed legs and clustered glinting eyes'], tags: 'insect small creepy', bias: { shot: 'macro:4' } },
    ladybug: { syn: 'ladybird|beetle', coat: 'shell', look: ['a glossy red shell with black spots'], tags: 'insect small', bias: { shot: 'macro:5' } },
    ant: { syn: 'ants', coat: 'shell', look: ['a segmented, glossy body'], tags: 'insect small', bias: { shot: 'macro:5' } },
    snail: { syn: 'slug', coat: 'shell', look: ['a spiraled, translucent shell and glistening body'], tags: 'small', bias: { shot: 'macro:5' } },
    frog: { syn: 'toad|tree frog', coat: 'skin', look: ['glossy speckled skin and bulging eyes'], hab: 'swamp:2, rainforest:2', tags: 'small', bias: { shot: 'macro:3' } },
    lizard: { syn: 'chameleon|gecko|iguana', coat: 'scales', look: ['finely textured, color-shifting scales'], tags: 'reptile small', bias: { shot: 'macro:3' } },
    snake: { syn: 'serpent|python|viper|snakes', coat: 'scales', look: ['glistening patterned scales'], tags: 'reptile' },
    cobra: { syn: 'king cobra', coat: 'scales', look: ['a flared hood and glistening olive scales'], tags: 'reptile india' },
    crocodile: { syn: 'alligator|croc|gator', coat: 'scales', look: ['an armored, ridged hide'], hab: 'river:3, swamp:2', tags: 'reptile predator' },
    turtle: { syn: 'sea turtle|tortoise|turtles', coat: 'shell', look: ['a patterned shell and leathery flippers'], hab: 'coral reef:3', tags: 'aquatic' },
    dolphin: { syn: 'dolphins', coat: 'skin', look: ['sleek, glistening grey skin'], hab: 'ocean:4', tags: 'aquatic' },
    whale: { syn: 'humpback|blue whale|orca|killer whale|whales', coat: 'skin', look: ['a vast, barnacled body'], hab: 'ocean:4', tags: 'aquatic big' },
    shark: { syn: 'great white|sharks', coat: 'skin', look: ['a torpedo-shaped body and rows of serrated teeth'], hab: 'underwater:4', tags: 'aquatic predator' },
    octopus: { syn: 'squid|cuttlefish', coat: 'skin', look: ['curling suckered tentacles and textured, color-shifting skin'], hab: 'underwater:4', tags: 'aquatic' },
    jellyfish: { syn: 'jellyfishes|jellies', coat: 'bell', look: ['a translucent pulsing bell trailing fine tentacles'], hab: 'underwater:5', tags: 'aquatic glow' },
    fish: { syn: 'fishes|school of fish|tropical fish', coat: 'scales', look: ['shimmering silver scales'], hab: 'underwater:4', tags: 'aquatic' },
    koi: { syn: 'koi fish|goldfish|carp', coat: 'scales', look: ['orange-and-white patterned scales and flowing fins'], hab: 'pond:5', tags: 'aquatic japan' },
    monkey: { syn: 'macaque|langur|ape|chimpanzee|chimp|orangutan|monkeys', coat: 'fur', look: ['expressive eyes and nimble hands'], hab: 'jungle:3, temple:1', tags: 'wild' },
    gorilla: { syn: 'silverback', coat: 'fur', look: ['a massive dark-furred frame with a silver back'], hab: 'jungle:4', tags: 'wild big' },
    cow: { syn: 'cattle|bull|ox|buffalo|water buffalo|cows', coat: 'hide', look: ['a dusty hide and gentle dark eyes'], hab: 'farm:3, village:2', tags: 'domestic' },
    camel: { syn: 'camels|dromedary', coat: 'fur', look: ['a shaggy sand-colored hump'], hab: 'desert:5', tags: 'desert' },
    goat: { syn: 'sheep|lamb|llama|alpaca|goats', coat: 'wool', look: ['a thick, tousled coat'], hab: 'meadow:3, farm:2', tags: 'domestic' },
    bat: { syn: 'bats', coat: 'fur', look: ['thin leathery wings'], hab: 'cave:4', tags: 'night creepy', bias: { time: 'night:3' } },
    dragon: { syn: 'wyvern|drake|dragons', coat: 'scales', look: ['iridescent armored scales, vast leathery wings and smoldering eyes'], hab: 'mountain:2, castle:2', tags: 'fantasy mythic big' },
    'chinese dragon': { syn: 'eastern dragon|lung dragon', coat: 'scales', look: ['a long serpentine body of jade and gold scales with flowing whiskers'], tags: 'fantasy mythic china' },
    phoenix: { syn: 'firebird', coat: 'feathers', look: ['feathers of living flame trailing embers'], tags: 'fantasy mythic fire' },
    unicorn: { syn: 'pegasus', coat: 'coat', look: ['a pearlescent coat and a spiraling horn'], hab: 'enchanted forest:4', tags: 'fantasy mythic' },
    griffin: { syn: 'gryphon|hippogriff', coat: 'feathers', look: ["an eagle's head and wings on a lion's muscular body"], hab: 'mountain:3', tags: 'fantasy mythic' },
    kraken: { syn: 'sea monster|leviathan|sea serpent', coat: 'skin', look: ['colossal barnacle-crusted tentacles'], hab: 'ocean:5', tags: 'fantasy mythic big horror' },
    dinosaur: { syn: 't-rex|tyrannosaurus|raptor|velociraptor|dino|triceratops|brachiosaurus', coat: 'scales', look: ['a scaled, heavily muscled hide and rows of teeth'], hab: 'jungle:3', tags: 'prehistoric big' },
    werewolf: { syn: 'lycan', coat: 'fur', look: ['matted dark fur over a hulking, half-human frame'], hab: 'forest:3', tags: 'horror', bias: { time: 'night:5' } },
    yeti: { syn: 'bigfoot|sasquatch', coat: 'fur', look: ['shaggy white fur'], hab: 'mountain:4', tags: 'mythic cold' },
    golem: { syn: 'stone giant|titan|troll|ogre|giant', coat: 'stone', look: ['a hulking body of moss-covered stone'], tags: 'fantasy big' },
    alien: { syn: 'extraterrestrial|aliens|alien creature', coat: 'skin', look: ['iridescent skin and large, dark reflective eyes'], hab: 'alien planet:4', tags: 'scifi' },
    robot: { syn: 'robots|droid|bot|automaton|humanoid robot', coat: 'plating', look: ['scuffed metal plating, exposed servos and glowing optical sensors'], tags: 'scifi robot' },
    mech: { syn: 'mecha|giant robot|battle mech', coat: 'plating', look: ['towering armored plating and hydraulic limbs'], tags: 'scifi big robot' },
    monster: { syn: 'beast|creature|monsters|kaiju', coat: 'hide', look: ['a hulking, textured body'], tags: 'horror big' },
  });
})();
