/* KB — visual styles / mediums and genres / eras.
 * style fields: medium (photo|film|illus|paint|3d|pixel|craft), lead [opening NP], vlead [video opening NP],
 *   tech [technique NP], quality [terms], neg [negative terms], sd [tags], mj ('--style raw' etc), cam (camera/film note)
 * genre fields: env [NP], wear ({f,m,n} | string), key [light], detail [NP], place bias, palette bias
 */
(function () {
  const SC = globalThis.SC;
  const PHOTO_Q = ['photorealistic', 'highly detailed', 'natural skin texture', 'accurate anatomy', 'true-to-life materials', 'coherent perspective'];
  const PHOTO_NEG = ['cartoon', 'illustration', 'CGI', '3D render', 'plastic-looking skin', 'oversaturated'];
  const ILL_NEG = ['photorealistic', 'photograph', '3D render', 'muddy colors'];

  SC.def('style', {
    photoreal: { adj: 'photorealistic', noun: 'photograph', syn: 'ultra realistic|ultra-realistic|ultrarealistic|hyper realistic|hyper-realistic|photorealistic|realistic|photo|photograph|photography|real|realism|hyperrealistic|hyper-realistic|hyperrealism|lifelike|true to life|raw photo|dslr photo', medium: 'photo',
      lead: ['A photorealistic photograph', 'A true-to-life photograph', 'A richly detailed photograph'], vlead: ['photorealistic live-action footage'],
      quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['RAW photo', 'photorealistic'], mj: '--style raw', cam: 'Shot on a full-frame mirrorless camera' },
    cinematic: { adj: 'cinematic', noun: 'film still', syn: 'film|cinema|film still|movie still|movie scene|film scene|filmic|movie|blockbuster|hollywood|cinematic shot|cinematography', medium: 'film',
      lead: ['A cinematic film still', 'A cinematic, photorealistic frame', 'A widescreen cinematic still'], vlead: ['cinematic live-action shot'],
      tech: ['anamorphic widescreen framing', 'filmic contrast with rolled-off highlights', 'subtle 35mm film grain'], quality: PHOTO_Q.concat(['professional color grading']), neg: PHOTO_NEG, sd: ['cinematic film still', 'color graded'], mj: '--style raw', cam: 'Shot on an ARRI Alexa cinema camera with cinema prime lenses', bias: { palette: 'teal-orange:1' } },
    'portrait photography': { syn: 'portrait|portraiture|portrait photo|studio portrait|editorial portrait', medium: 'photo',
      lead: ['A professional portrait photograph', 'An intimate portrait photograph'], quality: PHOTO_Q.concat(['sharp focus on the eyes', 'flattering skin tones']), neg: PHOTO_NEG, sd: ['portrait photography', 'sharp focus on eyes'], mj: '--style raw',
      bias: { shot: 'medium close-up:4, close-up:3', dof: 'bokeh:3' } },
    'street photography': { syn: 'street photo|street style photo|candid|candid photo|snapshot', medium: 'photo',
      lead: ['A candid street photograph', 'An unposed street photograph'], tech: ['a candid, decisive-moment feel', 'natural available light'], quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['street photography', 'candid'], mj: '--style raw', cam: 'Shot on a compact 35mm rangefinder',
      bias: { shot: 'medium shot:2, full shot:2' } },
    documentary: { syn: 'photojournalism|photojournalistic|national geographic|nat geo|reportage|documentary photo', medium: 'photo',
      lead: ['A documentary-style photograph', 'A photojournalistic image'], vlead: ['documentary-style footage'], tech: ['honest, unstaged realism', 'natural light only'], quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['documentary photography', 'photojournalism'], mj: '--style raw', bias: { move: 'handheld:3' } },
    fashion: { syn: 'fashion photography|editorial|vogue|high fashion|fashion editorial|magazine cover|lookbook', medium: 'photo',
      lead: ['A high-fashion editorial photograph', 'A glossy fashion editorial image'], tech: ['editorial styling and posing', 'polished retouching with retained skin texture'], quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['fashion editorial', 'haute couture'], mj: '--style raw --s 250' },
    'product photography': { syn: 'product shot|product photo|commercial photography|advertising|advertisement|ad shot|packshot|e-commerce', medium: 'photo',
      lead: ['A premium commercial product photograph', 'A studio product shot'], tech: ['crisp specular highlights', 'clean, precise reflections', 'immaculate surfaces'], quality: ['ultra-sharp detail', 'accurate materials', 'clean edges', 'commercial-grade finish'], neg: ['clutter', 'fingerprints', 'dust', 'distorted logo', 'text errors'], sd: ['product photography', 'studio lighting'], mj: '--style raw',
      bias: { place: 'studio:4', shot: 'medium shot:2, close-up:2' } },
    'food photography': { syn: 'food photo|food styling|culinary photography|food shot', medium: 'photo',
      lead: ['An appetizing food photograph', 'A mouthwatering editorial food photograph'], tech: ['fresh, glistening textures', 'carefully styled props'], quality: ['appetizing', 'crisp detail', 'true-to-life color'], neg: ['unappetizing', 'plastic food', 'messy'], sd: ['food photography', 'appetizing'], mj: '--style raw',
      bias: { place: 'tabletop:4', shot: 'close-up:3', angle: 'birds-eye:1, high angle:2', dof: 'bokeh:2' } },
    'wildlife photography': { syn: 'wildlife photo|nature photography|safari photo|animal photography', medium: 'photo',
      lead: ['A wildlife photograph', 'An award-winning wildlife photograph'], tech: ['natural animal behavior', 'crisp detail in fur and feathers'], quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['wildlife photography', 'telephoto'], mj: '--style raw', bias: { lens: '400mm telephoto:6' } },
    'landscape photography': { syn: 'landscape|landscape photo|scenic|scenery|vista|nature landscape', medium: 'photo',
      lead: ['A sweeping landscape photograph', 'A majestic landscape photograph'], tech: ['front-to-back sharpness', 'rich tonal range'], quality: ['highly detailed', 'rich tonal range', 'natural color'], neg: PHOTO_NEG, sd: ['landscape photography'], mj: '--style raw',
      bias: { shot: 'extreme wide shot:4', dof: 'deep focus:3' } },
    'film photography': { syn: 'analog|analogue|35mm film|film photo|kodak|portra|kodak portra|fuji film|fujifilm|cinestill|film grain|expired film', medium: 'photo',
      lead: ['An analog 35mm film photograph', 'A photograph shot on 35mm film'], tech: ['organic film grain', 'Kodak Portra 400 color response', 'gentle halation around highlights'], quality: PHOTO_Q, neg: PHOTO_NEG.concat(['digital sharpening']), sd: ['analog photo', 'film grain', 'kodak portra 400'], mj: '--style raw', bias: { palette: 'warm:1' } },
    polaroid: { syn: 'instant photo|instax|polaroid photo', medium: 'photo', lead: ['A faded Polaroid instant photograph'], tech: ['soft focus and washed-out instant-film color', 'a white instant-film border'], quality: ['authentic instant-film look'], neg: ['digital sharpness'], sd: ['polaroid', 'instant film'], mj: '--style raw', bias: { palette: 'desaturated:3' } },
    'black and white photo': { syn: 'black and white photography|monochrome photography|b&w photo|bw photo|noir photo', medium: 'photo', lead: ['A black-and-white photograph', 'A fine-art monochrome photograph'], tech: ['deep blacks and luminous highlights', 'fine silver-gelatin grain'], quality: PHOTO_Q, neg: ['color', 'oversaturated'], sd: ['black and white photography', 'monochrome'], mj: '--style raw', bias: { palette: 'bw:8' } },
    'long exposure': { syn: 'long-exposure photo|light painting|star trails', medium: 'photo', lead: ['A long-exposure photograph'], tech: ['silky smoothed water and clouds', 'streaking light trails'], quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['long exposure'], mj: '--style raw' },
    noir: { syn: 'film noir|neo noir|neo-noir|noir film|hardboiled', medium: 'film', lead: ['A film noir still', 'A moody film-noir frame'], vlead: ['film noir shot'], tech: ['hard shadows cutting across the frame', 'venetian-blind light patterns'], quality: PHOTO_Q, neg: PHOTO_NEG, sd: ['film noir', 'high contrast'], mj: '--style raw', bias: { palette: 'bw:5, high-contrast:3', time: 'night:3' }, add: { key: [['hard, angular low-key light slicing through shadow', 5]] } },

    anime: { syn: 'anime style|manga|manga style|japanese animation|cel shaded|cel-shaded|anime art|shonen|shojo', medium: 'illus',
      lead: ['An anime-style illustration', 'A detailed anime key visual'], vlead: ['anime-style animated shot'], tech: ['clean, confident linework', 'cel shading with soft gradients', 'expressive character design'], quality: ['masterpiece', 'best quality', 'highly detailed background art'], neg: ILL_NEG.concat(['bad anatomy', 'extra fingers']), sd: ['anime style', 'key visual', 'cel shading'], mj: '--niji 6' },
    ghibli: { syn: 'studio ghibli|ghibli style|miyazaki|hand-drawn anime|90s anime', medium: 'illus',
      lead: ['A hand-painted anime film frame in a gentle, nostalgic storybook style', 'A whimsical hand-painted anime illustration'], vlead: ['hand-drawn anime film shot'], tech: ['lush hand-painted watercolor backgrounds', 'soft, warm cel shading', 'gentle storybook atmosphere'], quality: ['masterpiece', 'best quality', 'painterly background detail'], neg: ILL_NEG, sd: ['hand-painted anime background', 'whimsical'], mj: '--niji 6', bias: { palette: 'pastel:2, warm:1' } },
    'comic book': { syn: 'comic|comics|graphic novel|marvel style|dc comics style|superhero comic|comic art', medium: 'illus', lead: ['A dynamic comic-book panel', 'A graphic-novel illustration'], tech: ['bold inked outlines', 'halftone dot shading', 'punchy flat color'], quality: ['dynamic composition', 'crisp inks'], neg: ILL_NEG, sd: ['comic book art', 'bold lineart', 'halftone'], mj: '--s 200', bias: { palette: 'vibrant:2' } },
    cartoon: { syn: 'cartoonish|cartoony|toon|animated|children book|childrens book|kids illustration|storybook|picture book', medium: 'illus', lead: ["A charming cartoon illustration", "A whimsical children's storybook illustration"], vlead: ['2D animated shot'], tech: ['rounded, friendly shapes', 'soft flat colors with gentle shading'], quality: ['clean shapes', 'appealing character design'], neg: ILL_NEG, sd: ['cartoon', 'storybook illustration'], mj: '--s 150' },
    pixar: { syn: 'pixar style|disney style|disney pixar|3d animated|3d animation|animated movie|dreamworks|3d cartoon|cgi animation', medium: '3d', lead: ['A 3D animated feature-film still', 'A charming 3D animated movie frame'], vlead: ['3D animated feature-film shot'], tech: ['appealing stylized character proportions', 'soft subsurface scattering on skin', 'expressive, oversized eyes'], quality: ['high-end feature animation quality', 'global illumination'], neg: ['photorealistic', 'uncanny', 'low poly'], sd: ['3d animation style', 'cute stylized character'], mj: '--s 200' },
    '3d render': { syn: '3d|cgi|octane render|octane|blender|unreal engine|unreal|render|redshift|c4d|cinema 4d|3d art', medium: '3d', lead: ['A high-end 3D render', 'A photoreal CGI render'], vlead: ['high-end CGI sequence'], tech: ['physically based materials', 'ray-traced reflections and global illumination'], quality: ['ultra-detailed', 'clean topology', 'ray-traced lighting'], neg: ['low poly', 'noisy render', 'artifacts'], sd: ['3d render', 'octane render', 'ray tracing'], mj: '--s 250' },
    isometric: { syn: 'isometric view|isometric art|diorama|miniature diorama', medium: '3d', lead: ['A cute isometric 3D diorama'], tech: ['a floating isometric cut-away base', 'tiny meticulously modeled details'], quality: ['clean', 'detailed'], neg: ['perspective distortion'], sd: ['isometric', 'diorama'], mj: '--s 200', bias: { angle: 'high angle:5', shot: 'wide shot:3' } },
    'low poly': { syn: 'lowpoly|low-poly|polygonal', medium: '3d', lead: ['A stylized low-poly 3D scene'], tech: ['faceted flat-shaded polygons', 'crisp geometric forms'], quality: ['clean geometry'], neg: ['high detail textures', 'noise'], sd: ['low poly'], mj: '' },
    claymation: { syn: 'clay|clay animation|stop motion|stop-motion|plasticine|aardman', medium: 'craft', lead: ['A handcrafted claymation scene', 'A stop-motion clay animation still'], vlead: ['stop-motion claymation shot'], tech: ['visible fingerprints in soft clay', 'miniature handmade sets', 'slightly imperfect handcrafted charm'], quality: ['tactile materials'], neg: ['photorealistic', 'smooth CGI'], sd: ['claymation', 'stop motion'], mj: '--s 200' },
    papercraft: { syn: 'paper cut|paper-cut|papercut|paper art|layered paper|origami style|kirigami', medium: 'craft', lead: ['A layered papercraft artwork'], tech: ['stacked cut-paper layers with soft drop shadows', 'visible paper fibers'], quality: ['tactile depth'], neg: ['photorealistic'], sd: ['paper cut art', 'layered paper'], mj: '' },
    watercolor: { syn: 'watercolour|water color|aquarelle|watercolor painting|watercolour painting', medium: 'paint', lead: ['A delicate watercolor painting', 'A loose, luminous watercolor painting'], vlead: ['animated watercolor painting'], tech: ['soft wet-on-wet washes', 'granulating pigment and blooming edges', 'the white of textured cold-press paper showing through'], quality: ['fine art', 'luminous color'], neg: ILL_NEG, sd: ['watercolor painting', 'wet on wet'], mj: '--s 250', bias: { palette: 'pastel:1' } },
    'oil painting': { syn: 'oil|oils|oil on canvas|classical painting|old masters|painting|fine art painting|impasto', medium: 'paint', lead: ['A rich oil painting on canvas', 'A masterful oil painting'], vlead: ['living oil painting animation'], tech: ['visible impasto brushstrokes', 'layered glazes with luminous depth', 'canvas weave beneath the paint'], quality: ['museum-quality fine art'], neg: ILL_NEG.concat(['digital look']), sd: ['oil painting', 'impasto', 'brushstrokes'], mj: '--s 300' },
    impressionist: { syn: 'impressionism|monet|monet style|van gogh|van gogh style|post-impressionist|plein air', medium: 'paint', lead: ['An impressionist painting', 'A plein-air impressionist canvas'], tech: ['broken, vibrant dabs of color', 'shimmering light captured in loose strokes'], quality: ['fine art'], neg: ILL_NEG, sd: ['impressionism', 'loose brushstrokes'], mj: '--s 300' },
    gouache: { syn: 'acrylic|acrylic painting|gouache painting|poster paint', medium: 'paint', lead: ['A gouache illustration', 'A bold acrylic painting'], tech: ['matte, opaque layers of paint', 'crisp painterly edges'], quality: ['fine art'], neg: ILL_NEG, sd: ['gouache'], mj: '--s 200' },
    'ink drawing': { syn: 'ink|pen and ink|sumi-e|ink wash|line art|lineart|linework', medium: 'illus', lead: ['An expressive ink drawing', 'A sumi-e ink wash painting'], tech: ['confident brush-and-ink strokes', 'washes of diluted ink'], quality: ['fine art'], neg: ['color', 'photorealistic'], sd: ['ink drawing', 'monochrome'], mj: '', bias: { palette: 'bw:4' } },
    sketch: { syn: 'pencil|pencil sketch|pencil drawing|graphite|charcoal|charcoal drawing|drawing|hand drawn|hand-drawn|concept sketch', medium: 'illus', lead: ['A detailed graphite pencil drawing', 'An expressive charcoal sketch'], tech: ['cross-hatched shading', 'smudged charcoal tones on textured paper'], quality: ['fine draftsmanship'], neg: ['color', 'photograph'], sd: ['pencil sketch', 'graphite'], mj: '', bias: { palette: 'bw:5' } },
    'digital painting': { syn: 'digital art|digital illustration|illustration|artstation|painterly|concept art|key art|splash art', medium: 'illus', lead: ['A highly detailed digital painting', 'A cinematic piece of concept art'], vlead: ['painterly animated concept-art shot'], tech: ['painterly brushwork with sharp focal detail', 'dramatic, cinematic lighting design'], quality: ['masterpiece', 'highly detailed', 'trending concept art quality'], neg: ILL_NEG, sd: ['digital painting', 'concept art', 'highly detailed'], mj: '--s 250' },
    'fantasy art': { syn: 'epic fantasy art|fantasy illustration|fantasy painting|d&d art|book cover art', medium: 'illus', lead: ['An epic fantasy illustration', 'A richly painted fantasy artwork'], tech: ['painterly detail with luminous magical light', 'grand, storytelling composition'], quality: ['masterpiece', 'intricate detail'], neg: ILL_NEG, sd: ['fantasy art', 'epic'], mj: '--s 300' },
    'matte painting': { syn: 'matte-painting|environment art|environment concept', medium: 'illus', lead: ['A vast cinematic matte painting'], tech: ['immense sense of scale', 'atmospheric perspective'], quality: ['masterpiece', 'intricate detail'], neg: ILL_NEG, sd: ['matte painting'], mj: '--s 250', bias: { shot: 'extreme wide shot:4' } },
    'pixel art': { syn: 'pixel|pixelated|8-bit|8 bit|16-bit|16 bit|retro game|sprite art|pixelart', medium: 'pixel', lead: ['A detailed 16-bit pixel art scene', 'A crisp pixel art illustration'], vlead: ['animated pixel art loop'], tech: ['a limited retro palette', 'crisp, hand-placed pixels with dithered shading'], quality: ['pixel-perfect'], neg: ['blurry', 'anti-aliased', 'photorealistic', 'gradient smoothing'], sd: ['pixel art', '16-bit'], mj: '' },
    'vector art': { syn: 'vector|flat design|flat illustration|minimalist illustration|flat art|corporate illustration|infographic style', medium: 'illus', lead: ['A clean flat vector illustration'], tech: ['bold geometric shapes', 'flat color with minimal gradients'], quality: ['clean edges'], neg: ['texture noise', 'photorealistic'], sd: ['flat vector illustration'], mj: '' },
    'ukiyo-e': { syn: 'ukiyoe|japanese woodblock|woodblock print|hokusai|hiroshige', medium: 'illus', lead: ['A Japanese ukiyo-e woodblock print'], tech: ['flat areas of color with bold outlines', 'visible woodgrain texture in the print', 'stylized waves and clouds'], quality: ['authentic print texture'], neg: ['photorealistic', '3D'], sd: ['ukiyo-e', 'woodblock print'], mj: '', bias: { palette: 'earthy:2' } },
    madhubani: { syn: 'mithila|madhubani painting|warli|warli art|gond|gond art|indian folk art|folk art|kalamkari|pattachitra', medium: 'illus', lead: ['An Indian folk-art painting in the Madhubani tradition'], tech: ['intricate line patterns filling every surface', 'bold natural pigments', 'stylized figures with large eyes', 'decorative floral borders'], quality: ['authentic handmade feel'], neg: ['photorealistic', '3D'], sd: ['madhubani painting', 'indian folk art'], mj: '', bias: { palette: 'vibrant:2, earthy:1' } },
    'mughal miniature': { syn: 'miniature painting|mughal painting|rajput painting|persian miniature|indian miniature', medium: 'paint', lead: ['A Mughal miniature painting'], tech: ['fine brushwork with gold-leaf accents', 'flattened perspective and ornamental borders', 'jewel-like mineral pigments'], quality: ['museum-quality detail'], neg: ['photorealistic', '3D'], sd: ['mughal miniature painting', 'gold leaf'], mj: '', bias: { palette: 'jewel:3' } },
    'art nouveau': { syn: 'mucha|alphonse mucha|nouveau', medium: 'illus', lead: ['An Art Nouveau poster illustration'], tech: ['flowing organic linework', 'ornamental halos and floral frames'], quality: ['elegant detail'], neg: ['photorealistic'], sd: ['art nouveau'], mj: '' },
    'art deco': { syn: 'deco|gatsby style|1920s poster', medium: 'illus', lead: ['An Art Deco illustration'], tech: ['bold geometric symmetry', 'gilded linework'], quality: ['elegant detail'], neg: ['photorealistic'], sd: ['art deco'], mj: '', bias: { palette: 'golden:3', comp: 'symmetry:3' } },
    'pop art': { syn: 'warhol|lichtenstein|pop-art', medium: 'illus', lead: ['A bold pop-art piece'], tech: ['Ben-Day dots and thick outlines', 'flat, loud primary colors'], quality: ['graphic punch'], neg: ['muted'], sd: ['pop art'], mj: '', bias: { palette: 'vibrant:4' } },
    surrealism: { syn: 'surreal|surrealist|dali|magritte|dreamlike art', medium: 'paint', lead: ['A surrealist painting', 'A surreal, dreamlike artwork'], tech: ['impossible scale and juxtaposition', 'meticulous, hyper-real rendering of an unreal idea'], quality: ['fine art'], neg: [], sd: ['surrealism'], mj: '--s 400 --weird 150', add: { atmo: ['a strange, dreamlike stillness'] } },
    minimalist: { syn: 'minimal|minimalism|clean|simple|simplistic', medium: 'photo', lead: ['A minimalist image'], tech: ['a restrained, uncluttered frame', 'a limited palette'], quality: ['clean', 'refined'], neg: ['clutter', 'busy background'], sd: ['minimalist'], mj: '--style raw', bias: { comp: 'negative-space:4' } },
    vaporwave: { syn: 'synthwave|retrowave|outrun|80s aesthetic|retro 80s|retro-futurism|retrofuturism', medium: 'illus', lead: ['A retro synthwave artwork'], tech: ['a glowing wireframe grid receding to a striped sunset', 'chrome and neon gradients'], quality: ['crisp retro graphics'], neg: [], sd: ['synthwave', 'retrowave'], mj: '', bias: { palette: 'neon colors:4', time: 'sunset:2, night:2' } },
    'stained glass': { syn: 'stained-glass|mosaic', medium: 'craft', lead: ['A luminous stained-glass window design'], tech: ['jewel-colored glass pieces bound by dark lead lines', 'light glowing through the glass'], quality: ['intricate'], neg: ['photorealistic'], sd: ['stained glass'], mj: '', bias: { palette: 'jewel:4' } },
    'tattoo art': { syn: 'tattoo|tattoo design|flash tattoo|traditional tattoo', medium: 'illus', lead: ['A bold tattoo flash design'], tech: ['heavy black outlines', 'limited saturated fills'], quality: ['clean linework'], neg: ['photorealistic', 'background clutter'], sd: ['tattoo design'], mj: '' },
    'vintage poster': { syn: 'poster|travel poster|retro poster|propaganda poster|screen print|risograph|riso|linocut', medium: 'illus', lead: ['A vintage screen-printed poster illustration'], tech: ['flat layered ink colors with slight misregistration', 'grainy print texture'], quality: ['bold graphic design'], neg: ['photorealistic', 'text errors'], sd: ['vintage poster', 'screen print'], mj: '' },
  });

  // every style gets an adjective + noun so leads can be composed ("Ultra-realistic cinematic photograph")
  const NOUNS = { photo: 'photograph', film: 'film still', illus: 'illustration', paint: 'painting', '3d': 'render', pixel: 'pixel art scene', craft: 'handcrafted artwork' };
  const ADJ = { fashion: 'high-fashion editorial', 'portrait photography': 'professional portrait', 'street photography': 'candid street', documentary: 'documentary-style',
    'film photography': 'analog 35mm film', 'product photography': 'premium commercial product', 'food photography': 'editorial food', 'wildlife photography': 'award-winning wildlife',
    'landscape photography': 'sweeping landscape', 'black and white photo': 'black-and-white', 'long exposure': 'long-exposure', noir: 'film noir', polaroid: 'Polaroid instant' };
  Object.values(SC.kb.style).forEach((e) => {
    if (!e.adj && ADJ[e.id]) e.adj = ADJ[e.id];
    if (!e.noun) e.noun = NOUNS[e.medium] || 'image';
    if (!e.adj) e.adj = e.id.replace(/ (photography|photo|painting|drawing|art|render|lens)$/, '').replace(/-/g, ' ');
  });

  SC.def('genre', {
    scifi: { adj: 'futuristic', syn: 'sci-fi|sci fi|science fiction|futuristic|future|space age|high-tech|high tech', env: ['sleek futuristic architecture', 'holographic interfaces glowing in the air'], wear: 'a sleek, seam-lined futuristic suit', key: [['cool, clean artificial light with glowing accents', 3]], bias: { palette: 'cool:2, teal-orange:1' }, tags: 'scifi tech' },
    cyberpunk: { adj: 'cyberpunk', syn: 'cyber punk|cyber-punk|blade runner|neo tokyo|dystopian future|tech noir', env: ['holographic billboards and dense neon signage', 'rain-slick streets crowded with cables and vendors', 'towering megastructures fading into smog'], wear: 'a reflective techwear jacket with glowing trim and cybernetic implants', key: [['saturated neon light in magenta and cyan', 5]], detail: ['glitching holographic ads', 'cybernetic implants catching the light'], bias: { place: 'cyberpunk city:3', palette: 'neon colors:4', time: 'night:4' }, tags: 'scifi neon urban' },
    steampunk: { adj: 'steampunk', syn: 'steam punk|victorian sci-fi|clockwork', env: ['brass gears, pipes and hissing steam valves', 'riveted copper machinery'], wear: { f: 'a corseted Victorian dress with brass goggles and leather straps', m: 'a waistcoat, leather harness and brass goggles', n: 'a leather duster covered in brass gadgets' }, detail: ['ticking clockwork mechanisms'], bias: { palette: 'golden:2, earthy:2' }, tags: 'historic tech' },
    solarpunk: { adj: 'solarpunk', syn: 'solar punk|eco futurism|green future|eco-futuristic', env: ['gleaming towers draped in hanging gardens', 'solar sails and wind turbines woven into architecture'], wear: 'breathable natural-fiber clothing', bias: { palette: 'vibrant:2, forest:2', time: 'morning:2' }, tags: 'scifi nature hopeful' },
    'post-apocalyptic': { adj: 'post-apocalyptic', syn: 'post apocalyptic|apocalyptic|dystopian|dystopia|end of the world|fallout|mad max|wasteland style', env: ['collapsed buildings reclaimed by weeds', 'rusted, abandoned vehicles', 'makeshift barricades'], wear: 'patched scavenged gear and a dust-caked respirator', bias: { place: 'wasteland:3', palette: 'desaturated:3, earthy:2' }, tags: 'decay gritty' },
    fantasy: { adj: 'fantasy', syn: 'high fantasy|epic fantasy|mythical|magical realm|sword and sorcery|lord of the rings', env: ['ancient stone ruins carved with glowing runes', 'impossibly tall spires in the distance'], wear: 'an embroidered cloak over finely crafted leather armor', key: [['magical, glowing light with volumetric rays', 3]], detail: ['drifting motes of magical light'], bias: { palette: 'jewel:2, golden:1' }, tags: 'fantasy magic' },
    'dark fantasy': { adj: 'dark-fantasy', syn: 'grimdark|dark souls|elden ring|gothic fantasy|bloodborne', env: ['twisted dead trees and crumbling gothic stonework', 'bones scattered in the ash'], wear: 'battered blackened armor and a tattered cloak', key: [['cold, sickly light from a veiled sky', 4]], bias: { palette: 'desaturated:3, crimson-black:2' }, tags: 'fantasy dark' },
    horror: { syn: 'scary movie|horror movie|nightmare|creepy horror|slasher', env: ['long shadows in every corner', 'something indistinct lurking out of focus'], key: [['cold, flickering light with deep, swallowing shadows', 5]], detail: ['a barely visible figure in the darkness'], bias: { palette: 'desaturated:3, crimson-black:1', time: 'night:3' }, tags: 'horror dark' },
    gothic: { adj: 'gothic', syn: 'goth|victorian gothic|gothic horror', env: ['pointed arches, gargoyles and wrought iron', 'candelabras dripping with wax'], wear: { f: 'a black lace high-collared gown', m: 'a black frock coat and cravat', n: 'layered black velvet' }, bias: { palette: 'crimson-black:3', time: 'night:2' }, tags: 'dark historic' },
    medieval: { adj: 'medieval', syn: 'middle ages|dark ages|feudal', env: ['timber-framed houses and muddy cobbled lanes', 'torches in iron sconces'], wear: { f: 'a rough-spun linen dress and wool shawl', m: 'a rough-spun linen tunic and wool cloak', n: 'rough-spun linen and wool' }, bias: { palette: 'earthy:3' }, tags: 'historic' },
    ancient: { adj: 'ancient', syn: 'antiquity|ancient times|classical antiquity|ancient rome|ancient greece|roman|greek mythology|spartan', env: ['marble colonnades and weathered statues'], wear: 'a draped linen tunic and sandals', bias: { palette: 'earthy:2, golden:1' }, tags: 'historic' },
    'ancient egypt': { adj: 'ancient Egyptian', syn: 'egyptian mythology|pharaonic|ancient egyptian', env: ['colossal hieroglyph-covered columns', 'golden sarcophagi and oil lamps'], wear: 'white linen with a broad jeweled collar', bias: { palette: 'golden:3' }, tags: 'historic egypt' },
    mughal: { adj: 'Mughal-era', syn: 'mughal era|mughal empire|nawabi|royal india|maharaja era', env: ['white marble arches with pietra dura inlay', 'fountains in symmetrical charbagh gardens', 'silk canopies and hanging brass lamps'], wear: { f: 'a jewel-embroidered anarkali with a sheer dupatta', m: 'a silk sherwani with a jeweled turban', n: 'embroidered royal silks' }, bias: { palette: 'jewel:3, golden:2' }, tags: 'historic india royal' },
    victorian: { adj: 'Victorian', syn: '1800s|19th century|edwardian|regency|bridgerton', env: ['gaslit streets and ornate ironwork', 'heavy velvet drapes and oil portraits'], wear: { f: 'a high-collared Victorian dress', m: 'a tailored frock coat and waistcoat', n: 'Victorian-era clothing' }, bias: { palette: 'sepia:2, earthy:1' }, tags: 'historic' },
    '1920s': { adj: '1920s', syn: 'twenties|roaring twenties|jazz age|prohibition era', env: ['Art Deco details and brass fixtures'], wear: { f: 'a beaded flapper dress with a feathered headband', m: 'a three-piece pinstripe suit and fedora', n: '1920s evening wear' }, bias: { palette: 'sepia:2, golden:2' }, tags: 'historic vintage' },
    '1950s': { adj: '1950s', syn: 'fifties|50s|mid-century|midcentury|rockabilly', env: ['chrome diners and pastel appliances'], wear: { f: 'a polka-dot swing dress', m: 'a leather jacket and rolled-cuff jeans', n: '1950s casual wear' }, bias: { palette: 'pastel:3' }, tags: 'vintage' },
    '1970s': { adj: '1970s', syn: 'seventies|70s|disco era|groovy', env: ['wood paneling and shag carpet', 'orange and brown decor'], wear: { f: 'flared jeans and a patterned blouse', m: 'a wide-collared shirt and corduroy flares', n: '1970s clothing' }, bias: { palette: 'earthy:3, warm:2' }, add: { texture: ['warm, faded 1970s film stock'] }, tags: 'vintage' },
    '1980s': { adj: '1980s', syn: 'eighties|80s|retro eighties', env: ['arcade cabinets and neon trim', 'boomboxes and cassette tapes'], wear: { f: 'an oversized neon windbreaker and high-waisted jeans', m: 'a bomber jacket and high-top sneakers', n: '1980s streetwear' }, bias: { palette: 'neon colors:2, vibrant:2' }, tags: 'vintage neon' },
    '1990s': { adj: '1990s', syn: 'nineties|90s|y2k', env: ['CRT monitors and disposable cameras'], wear: { f: 'baggy jeans and a cropped flannel shirt', m: 'a baggy flannel shirt and jeans', n: '1990s grunge clothing' }, add: { texture: ['a slightly flashy point-and-shoot film look'] }, tags: 'vintage' },
    retro: { adj: 'vintage', syn: 'vintage|old-fashioned|old fashioned|antique|classic|old school|bygone era|nostalgic era', env: ['period-accurate vintage details'], add: { texture: ['a subtly faded, vintage finish'] }, bias: { palette: 'sepia:2, desaturated:1' }, tags: 'vintage' },
    western: { adj: 'Wild West', syn: 'wild west|old west|spaghetti western|frontier', env: ['a dusty frontier town with wooden storefronts', 'tumbleweeds and hitching posts'], wear: 'a dusty duster coat and wide-brimmed hat', bias: { place: 'desert:2', palette: 'earthy:3, warm:2' }, tags: 'western' },
    mythological: { adj: 'mythic', syn: 'mythology|myth|legend|legendary tale|hindu mythology|mahabharata|ramayana|norse mythology|divine|god|goddess|deity', env: ['celestial clouds parting around divine figures', 'ornate golden temples in the heavens'], wear: 'divine silks and ornate golden ornaments', key: [['radiant divine light from above', 4]], bias: { palette: 'golden:3, jewel:2' }, tags: 'sacred fantasy' },
    'fairy tale': { adj: 'fairy-tale', syn: 'fairytale|fairy-tale|storybook tale|once upon a time|enchanted', env: ['a winding path to a turreted cottage', 'toadstools and glowing flowers'], key: [['warm, enchanted light', 3]], bias: { place: 'enchanted forest:2', palette: 'pastel:2' }, tags: 'fantasy whimsical' },
    military: { adj: 'wartime', syn: 'war|warfare|combat|battle scene|ww2|world war|wwii|army', env: ['sandbags, barbed wire and shell craters'], wear: 'mud-streaked combat fatigues and a helmet', bias: { palette: 'desaturated:3, earthy:2', place: 'battlefield:2' }, tags: 'war gritty' },
    bollywood: { adj: 'Bollywood-style', syn: 'bollywood style|indian cinema|desi cinema|filmi|tollywood', env: ['swirling backup dancers', 'a lavish, color-saturated set'], wear: { f: 'a shimmering sequined saree with a flowing pallu', m: 'a tailored sherwani', n: 'glamorous festive clothing' }, key: [['glamorous, glowing high-key light', 3]], bias: { palette: 'vibrant:4, jewel:2', move: 'crane-up:2, orbit:2' }, tags: 'india festive dramatic' },
    'space opera': { adj: 'space-opera', syn: 'star wars|star trek|galactic|intergalactic|space battle|space war', env: ['fleets of starships against a nebula', 'laser fire streaking through space'], bias: { place: 'outer space:3', palette: 'cool:2, teal-orange:1' }, tags: 'scifi space' },
  });
})();
