/* KB — objects, vehicles, food, products, plants, sky objects, effects.
 * thing fields: type (veh|hold|food|product|arch|plant|sky|fx), look [NP], hab, light (emitted light NP)
 */
(function () {
  const SC = globalThis.SC;

  SC.def('thing', {
    // ---- vehicles ----
    car: { syn: 'automobile|sedan|suv', type: 'veh', look: ['sleek bodywork catching the light'], tags: 'vehicle' },
    'sports car': { syn: 'supercar|race car|racecar|lamborghini|ferrari|porsche', type: 'veh', look: ['a low, aerodynamic body in glossy paint'], tags: 'vehicle fast' },
    'vintage car': { syn: 'classic car|old car|retro car|oldtimer|ambassador car', type: 'veh', look: ['rounded, chrome-trimmed bodywork'], tags: 'vehicle vintage' },
    motorcycle: { syn: 'motorbike|royal enfield|harley|superbike|dirt bike', type: 'veh', look: ['a chrome-and-black engine block'], tags: 'vehicle' },
    bicycle: { syn: 'bike|cycle|bmx', type: 'veh', look: ['a slim steel frame'], tags: 'vehicle' },
    scooter: { syn: 'vespa|moped', type: 'veh', look: ['a rounded, pastel-painted body'], tags: 'vehicle' },
    bus: { syn: 'double decker|double-decker bus|school bus', type: 'veh', look: ['a long, boxy body with fogged windows'], tags: 'vehicle urban' },
    train: { syn: 'locomotive|steam train|local train|bullet train|metro train', type: 'veh', look: ['a long line of weathered carriages'], hab: 'railway station:3', tags: 'vehicle' },
    tram: { syn: 'streetcar|trolley', type: 'veh', look: ['a narrow painted carriage on steel rails'], tags: 'vehicle urban' },
    taxi: { syn: 'cab|yellow cab|kaali peeli|black and yellow taxi', type: 'veh', look: ['a dented black-and-yellow body'], tags: 'vehicle urban' },
    'auto rickshaw': { syn: 'rickshaw|autorickshaw|tuk tuk|tuk-tuk|auto', type: 'veh', look: ['a green-and-yellow three-wheeled body with a canvas roof'], hab: 'street:3', tags: 'vehicle india street' },
    truck: { syn: 'lorry|pickup truck|pickup', type: 'veh', look: ['a mud-spattered chassis'], tags: 'vehicle' },
    boat: { syn: 'rowboat|canoe|kayak|dinghy|gondola|shikara|fishing boat', type: 'veh', look: ['a weathered wooden hull'], hab: 'lake:3', tags: 'vehicle water' },
    sailboat: { syn: 'yacht|sailing ship|sailboats', type: 'veh', look: ['taut white sails'], hab: 'ocean:3', tags: 'vehicle water' },
    ship: { syn: 'cargo ship|ocean liner|galleon|battleship|ships', type: 'veh', look: ['a towering steel hull'], hab: 'ocean:3', tags: 'vehicle water big' },
    'pirate ship': { type: 'veh', look: ['tattered black sails and a carved wooden hull'], hab: 'ocean:4', tags: 'vehicle water nautical historic' },
    submarine: { type: 'veh', look: ['a riveted steel hull'], hab: 'underwater:4', tags: 'vehicle' },
    airplane: { syn: 'plane|aircraft|airliner|jet|jet plane|aeroplane', type: 'veh', look: ['polished aluminium wings'], hab: 'sky:3', tags: 'vehicle flying' },
    'fighter jet': { syn: 'fighter plane|warplane', type: 'veh', look: ['a sharp, angular grey fuselage'], hab: 'sky:3', tags: 'vehicle flying fast military' },
    helicopter: { syn: 'chopper', type: 'veh', look: ['spinning rotor blades'], hab: 'sky:2', tags: 'vehicle flying' },
    airship: { syn: 'zeppelin|blimp|dirigible|airships|sky ship', type: 'veh', look: ['a vast riveted envelope with brass propellers'], hab: 'sky:4', tags: 'vehicle flying' },
    'hot air balloon': { syn: 'air balloon|hot air balloons', type: 'veh', look: ['a vast striped envelope glowing from within'], hab: 'sky:3', tags: 'vehicle flying' },
    rocket: { syn: 'space rocket|rocket ship|launch vehicle|rockets', type: 'veh', look: ['a towering white fuselage streaked with frost'], hab: 'launch pad:6', tags: 'vehicle space' },
    spaceship: { syn: 'spacecraft|starship|space ship|ufo|flying saucer|spaceships', type: 'veh', look: ['a sleek hull of panelled alloy with glowing thrusters'], hab: 'outer space:4', tags: 'vehicle scifi space' },
    'space station': { syn: 'orbital station|iss', type: 'veh', look: ['sprawling solar arrays and modular hull sections'], hab: 'outer space:6', tags: 'scifi space' },
    tank: { syn: 'battle tank|armored vehicle', type: 'veh', look: ['mud-caked armor plating and a heavy turret'], tags: 'vehicle military' },
    tractor: { syn: 'bullock cart|cart|wagon|horse cart', type: 'veh', look: ['mud-caked wheels'], hab: 'farm:3', tags: 'vehicle rural' },

    // ---- holdable props ----
    umbrella: { syn: 'umbrellas|parasol', type: 'hold', look: ['a taut canopy'] },
    lantern: { syn: 'lanterns|oil lantern|paper lantern', type: 'hold', light: 'the warm glow of a lantern', tags: 'glow' },
    candle: { syn: 'candles|candlestick', type: 'hold', light: 'a small candle flame', tags: 'glow' },
    diya: { syn: 'diyas|oil lamp|clay lamp|deepam', type: 'hold', light: 'the flickering flame of clay diyas', tags: 'glow india festive' },
    book: { real: 'with natural page curvature and paper texture', neg: 'illegible floating text, warped pages', syn: 'novel|paperback|books|journal|diary|notebook', type: 'hold', look: ['worn, dog-eared pages'] },
    letter: { syn: 'envelope|love letter|letters', type: 'hold', look: ['creased, handwritten paper'] },
    sword: { real: 'with a believable weight, grip and edge reflections', neg: 'bent blade, floating sword, sword merging with hand', syn: 'blade|longsword|swords|sabre|saber', type: 'hold', look: ['a gleaming, nicked steel blade'], tags: 'weapon' },
    katana: { type: 'hold', look: ['a curved blade with a wrapped hilt'], tags: 'weapon japan' },
    'bow and arrow': { syn: 'bow|longbow|arrow|arrows|crossbow', type: 'hold', look: ['a taut recurve bow'], tags: 'weapon' },
    gun: { syn: 'pistol|revolver|rifle|firearm|blaster', type: 'hold', look: ['matte gunmetal'], tags: 'weapon' },
    staff: { syn: 'magic staff|wand|scepter', type: 'hold', look: ['carved runes along its length'], tags: 'magic' },
    shield: { type: 'hold', look: ['a dented, painted face'] },
    guitar: { real: 'with correct strings, frets and hand placement', neg: 'extra strings, warped guitar neck, wrong finger placement', syn: 'acoustic guitar|electric guitar|ukulele|bass guitar', type: 'hold', look: ['a worn wooden body'], tags: 'music' },
    violin: { syn: 'fiddle|cello', type: 'hold', look: ['a varnished spruce body'], tags: 'music' },
    flute: { syn: 'bansuri|saxophone|trumpet|clarinet', type: 'hold', tags: 'music' },
    sitar: { syn: 'veena|tabla', type: 'hold', look: ['a long carved neck and gourd resonator'], tags: 'music india' },
    piano: { syn: 'grand piano|keyboard', type: 'arch', look: ['glossy black lacquer and ivory keys'], tags: 'music' },
    drums: { syn: 'drum|dhol|dhak|drummers|nagada|djembe', type: 'hold', look: ['taut hide drumheads and painted wooden shells'], tags: 'music festive' },
    microphone: { syn: 'mic|vintage microphone', type: 'hold', tags: 'music' },
    camera: { real: 'with accurate controls, lens markings and reflections', neg: 'distorted camera, floating camera', syn: 'dslr|film camera|polaroid camera|vintage camera', type: 'hold', look: ['a leather strap and brass-trimmed body'] },
    phone: { n: 'smartphone', syn: 'smartphone|cellphone|mobile phone|iphone|mobile', type: 'hold', light: 'the cold glow of a phone screen', real: 'with a realistic camera lens and natural reflections on the screen', neg: 'distorted smartphone, floating smartphone, phone merging with fingers' },
    laptop: { syn: 'computer|macbook|notebook computer', type: 'hold', light: 'blue screen glow' , tags: 'tech' },
    headphones: { plural: 1, syn: 'headset|earphones', type: 'hold' },
    'cup of coffee': { syn: 'coffee|latte|espresso|coffee cup|cappuccino|mug', type: 'hold', look: ['steam curling from the rim'], tags: 'food cozy' },
    'cup of tea': { syn: 'tea|teacup|green tea|matcha', type: 'hold', look: ['steam curling from the rim'], tags: 'food cozy' },
    chai: { n: 'cup of chai', syn: 'masala chai|cutting chai|kulhad|kulhad chai', type: 'hold', look: ['steam curling from a clay kulhad of milky chai'], tags: 'food india cozy' },
    'wine glass': { syn: 'wine|glass of wine|champagne|champagne glass', type: 'hold', tags: 'elegant' },
    bouquet: { syn: 'bunch of flowers|flower bouquet', type: 'hold', look: ['loosely tied stems and fresh blooms'] },
    balloon: { syn: 'balloons', type: 'hold', tags: 'playful' },
    kite: { syn: 'kites|patang', type: 'hold', look: ['a bright paper kite tugging at its string'], tags: 'playful' },
    backpack: { syn: 'rucksack|satchel|bag', type: 'hold' },
    suitcase: { syn: 'luggage|travel bag|briefcase', type: 'hold', look: ['scuffed leather corners'] },
    map: { syn: 'old map|treasure map|scroll', type: 'hold', look: ['creased, sepia-toned paper'] },
    gift: { syn: 'present|gift box|presents', type: 'hold', look: ['a neatly tied ribbon'] },
    crown: { syn: 'tiara', type: 'hold', look: ['jewels set in worked gold'], tags: 'royal' },
    mask: { syn: 'venetian mask|masquerade mask|gas mask|oni mask', type: 'hold', tags: 'mystery' },
    orb: { syn: 'crystal ball|glowing orb|magic orb', type: 'hold', light: 'the inner glow of a crystal orb', tags: 'magic glow' },
    crystal: { syn: 'gemstone|gem|crystals|diamond', type: 'hold', look: ['faceted surfaces scattering light'], tags: 'glow' },
    skull: { syn: 'skulls', type: 'hold', tags: 'dark' },
    key: { syn: 'old key|skeleton key|keys', type: 'hold' },
    mirror: { syn: 'hand mirror|mirrors', type: 'hold', tags: 'reflection' },
    clock: { syn: 'pocket watch|hourglass|clocks', type: 'hold', tags: 'time' },
    telescope: { syn: 'binoculars|spyglass', type: 'hold' },
    torch: { syn: 'flaming torch|torches|flashlight', type: 'hold', light: 'the flickering flare of a torch', tags: 'fire glow' },
    cigarette: { syn: 'cigar|pipe|hookah', type: 'hold', look: ['a thin curl of smoke'], tags: 'smoke' },
    paintbrush: { syn: 'brush|paint brush|palette knife', type: 'hold', tags: 'art' },
    'fishing rod': { syn: 'fishing pole', type: 'hold', tags: 'water' },
    nets: { syn: 'net|fishing net|fishing nets', type: 'hold', plural: 1, look: ['knotted, salt-stiff mesh'], tags: 'water' },
    surfboard: { syn: 'surf board|skateboard|snowboard', type: 'hold', tags: 'sport' },
    teddy: { syn: 'teddy bear|stuffed toy|plush toy|toy', type: 'hold', tags: 'cute' },

    // ---- sports (used as objects of "play") ----
    cricket: { syn: 'cricket match|gully cricket', type: 'sport', mass: 1, tags: 'sport india', act: { pose: 'mid-swing with the bat, the ball blurring toward the camera', v: ['[play] cricket with focused energy {at}', 'the batter [swing] hard and the ball [fly] off the bat', '[cheer] and [run] between the makeshift wickets'] } },
    football: { syn: 'soccer|soccer ball|football match', type: 'sport', mass: 1, tags: 'sport', act: { pose: 'mid-kick, the ball just leaving the foot', v: ['[play] football {at}', '[dribble] past each other, kicking up dust', 'the ball [fly] toward the goal'] } },
    basketball: { syn: 'hoops|basketball game', type: 'sport', mass: 1, tags: 'sport', act: { pose: 'rising for a jump shot', v: ['[play] basketball {at}', '[drive] toward the hoop', 'the ball [arc] through the air toward the net'] } },
    tennis: { syn: 'badminton|table tennis|volleyball|golf|hockey|baseball|chess|kabaddi', type: 'sport', mass: 1, tags: 'sport', act: { pose: 'caught mid-play, fully focused', v: ['[play] with focused intensity {at}', '[react] quickly to the next move', '[pause] to catch a breath'] } },
    // ---- food ----
    ramen: { n: 'bowl of ramen', syn: 'noodle soup|pho|udon', type: 'food', look: ['rich golden broth, springy noodles, a halved jammy egg and scattered scallions'], tags: 'food japan' },
    sushi: { n: 'platter of sushi', syn: 'sashimi|nigiri', type: 'food', look: ['glistening slices of fish over neatly pressed rice'], tags: 'food japan' },
    pizza: { syn: 'margherita', type: 'food', look: ['a blistered crust, bubbling mozzarella and torn basil'], tags: 'food' },
    burger: { syn: 'cheeseburger|hamburger|sandwich', type: 'food', look: ['a glossy toasted bun, melting cheese and crisp lettuce'], tags: 'food' },
    biryani: { n: 'plate of biryani', syn: 'pulao', type: 'food', look: ['fragrant saffron-streaked rice, tender meat and fried onions'], tags: 'food india' },
    dosa: { syn: 'masala dosa|idli|idli sambar|uttapam', type: 'food', look: ['a crisp golden crepe with coconut chutney and sambar'], tags: 'food india' },
    thali: { n: 'Indian thali', syn: 'indian meal|indian food|curry|dal|paneer|butter chicken', type: 'food', look: ['small steel bowls of curries, dal, rice and warm flatbread'], tags: 'food india' },
    'street food': { n: 'plate of Indian street food', syn: 'chaat|pani puri|golgappa|vada pav|pav bhaji|samosa|samosas|pakora|pakoras|bhel puri', type: 'food', look: ['crisp golden textures, tangy chutneys and a scatter of fresh coriander'], tags: 'food india street' },
    jalebi: { n: 'plate of Indian sweets', syn: 'sweets|mithai|gulab jamun|ladoo|laddu|barfi', type: 'food', look: ['glossy, syrup-soaked sweets'], tags: 'food india festive' },
    dumplings: { n: 'steamer of dumplings', syn: 'momos|dim sum|gyoza|bao', type: 'food', look: ['pleated translucent wrappers glistening with steam'], tags: 'food' },
    cake: { syn: 'birthday cake|pastry|cupcake|cupcakes|dessert|cheesecake|tart', type: 'food', look: ['layers of soft sponge and glossy frosting'], tags: 'food' },
    bread: { n: 'loaf of bread', syn: 'croissant|baguette|sourdough|bakery bread|loaf', type: 'food', look: ['a crackled, deeply golden crust'], tags: 'food' },
    fruit: { n: 'bowl of fresh fruit', syn: 'fruits|apple|apples|oranges|mango|mangoes|strawberries|berries|grapes|lemons|cherries|fruit bowl', type: 'food', look: ['dew-beaded skins in saturated natural color'], tags: 'food' },
    'ice cream': { n: 'scoop of ice cream', syn: 'gelato|kulfi|sundae|popsicle', type: 'food', look: ['slowly melting scoops'], tags: 'food' },
    cocktail: { syn: 'drink|mocktail|martini|whiskey|whisky|margarita|lemonade|juice', type: 'food', look: ['condensation beading on cold glass'], tags: 'food' },
    chocolate: { n: 'bar of dark chocolate', syn: 'chocolates|cocoa|truffles', type: 'food', look: ['glossy tempered chocolate'], tags: 'food' },
    pancakes: { n: 'stack of pancakes', syn: 'waffles|breakfast', type: 'food', look: ['a golden stack drizzled with syrup'], tags: 'food' },
    steak: { n: 'grilled steak', syn: 'barbecue|bbq|grilled meat|kebab|kebabs|tandoori', type: 'food', look: ['a charred, glistening sear'], tags: 'food' },
    salad: { n: 'bowl of salad', syn: 'bowl|poke bowl|buddha bowl', type: 'food', look: ['crisp greens and bright, fresh ingredients'], tags: 'food' },

    // ---- products ----
    perfume: { n: 'perfume bottle', syn: 'perfume bottle|fragrance|cologne', type: 'product', look: ['a faceted glass bottle with a weighted gold cap'], tags: 'product luxury' },
    watch: { syn: 'wristwatch|timepiece|chronograph|smartwatch', type: 'product', look: ['a brushed-steel case and sapphire crystal'], tags: 'product luxury' },
    sneakers: { plural: 1, syn: 'shoes|trainers|sneaker|boots|heels', type: 'product', look: ['precise stitching and layered materials'], tags: 'product fashion' },
    handbag: { syn: 'purse|clutch|tote bag|leather bag', type: 'product', look: ['supple leather and polished hardware'], tags: 'product fashion luxury' },
    cosmetics: { n: 'beauty products', syn: 'lipstick|makeup|skincare|serum|cream jar|nail polish|beauty product', type: 'product', look: ['glossy packaging and creamy textures'], tags: 'product beauty' },
    jewelry: { syn: 'jewellery|ring|necklace|earrings|bracelet|pendant|bangles', type: 'product', look: ['polished metal and precisely cut stones'], tags: 'product luxury' },
    sunglasses: { plural: 1, syn: 'glasses|eyewear|spectacles', type: 'product', look: ['glossy frames and reflective lenses'], tags: 'product fashion' },
    bottle: { syn: 'water bottle|glass bottle|soda can|can|energy drink|beer bottle|beer', type: 'product', look: ['cold condensation on the surface'], tags: 'product' },

    // ---- structures & set pieces ----
    lighthouse: { type: 'arch', look: ['a tall striped tower crowned with a lantern room'], light: 'the sweeping beam of the lighthouse lamp', hab: 'cliff:4', tags: 'coastal' },
    windmill: { syn: 'windmills|wind turbine', type: 'arch', look: ['broad slowly turning sails'], hab: 'field:3', tags: 'rural' },
    tower: { syn: 'clock tower|watchtower|spire', type: 'arch', look: ['weathered stone rising high above'], tags: 'architecture' },
    statue: { syn: 'sculpture|monument|idol|buddha statue', type: 'arch', look: ['weathered stone and patinated bronze'], tags: 'architecture' },
    fountain: { type: 'arch', look: ['arcs of water spilling into a carved basin'], tags: 'water' },
    treehouse: { syn: 'tree house', type: 'arch', look: ['patchwork planks nestled among branches'], hab: 'forest:3', tags: 'whimsical' },
    tent: { syn: 'campsite|camp|tents', type: 'arch', look: ['a canvas shelter glowing from within'], hab: 'forest:2, mountain:2', tags: 'adventure' },
    fireplace: { syn: 'hearth|fire place|chimney fire|log fire', type: 'arch', light: 'warm, flickering firelight from the hearth', hab: 'living room:4', tags: 'cozy fire glow' },
    bench: { syn: 'park bench', type: 'arch', look: ['worn wooden slats'], hab: 'park:3' },
    swing: { syn: 'rope swing|jhula', type: 'arch', hab: 'garden:2' },
    door: { syn: 'doorway|gate|portal|gateway', type: 'arch', look: ['an ornate, weathered frame'], tags: 'threshold' },
    window: { syn: 'windows|window sill|windowsill', type: 'arch', tags: 'window' },
    'torii gate': { syn: 'torii', type: 'arch', look: ['vermilion lacquered pillars'], tags: 'japan sacred' },
    'phone booth': { syn: 'telephone booth|phone box', type: 'arch', look: ['a red-painted frame and fogged glass'], tags: 'urban vintage' },
    'city lights': { syn: 'lights|skyline lights|bokeh lights|glittering lights', type: 'fx', plural: 1, light: 'the glittering lights of the city', tags: 'urban glow night' },
    'fairy lights': { syn: 'string lights|twinkle lights|festoon lights|diwali lights', type: 'fx', plural: 1, light: 'warm strings of fairy lights', tags: 'glow cozy festive' },
    'street lamp': { syn: 'lamppost|lamp post|street lamps', type: 'arch', light: 'a lone street lamp', tags: 'urban' },
    throne: { type: 'arch', look: ['a high-backed seat of carved gold'], hab: 'throne room:5', tags: 'royal' },
    'vending machine': { syn: 'vending machines', type: 'arch', light: 'the humming glow of a vending machine', tags: 'japan urban' },
    'neon sign': { syn: 'neon signs|signboard|billboard|billboards', type: 'arch', light: 'buzzing neon signage', tags: 'urban neon' },
    screen: { syn: 'monitor|screens|tv|television|hologram|holograms|holographic display', type: 'arch', light: 'the glow of screens', tags: 'tech' },
    mandala: { syn: 'rangoli|kolam', type: 'arch', look: ['intricate symmetrical patterns in bright powder'], tags: 'india festive' },

    // ---- plants ----
    tree: { syn: 'trees|oak|oak tree|old tree|maple tree', type: 'plant', look: ['gnarled bark and a broad canopy'], tags: 'nature' },
    'cherry blossom': { syn: 'cherry blossoms|sakura|blossoms|cherry tree|blossom tree', type: 'plant', look: ['clouds of pale pink blossom'], tags: 'nature japan spring' },
    'banyan tree': { syn: 'banyan|peepal tree|peepal|bodhi tree', type: 'plant', look: ['aerial roots cascading from sprawling branches'], tags: 'nature india' },
    'palm tree': { syn: 'palm trees|palms|coconut tree|coconut trees', type: 'plant', look: ['fronds swaying against the sky'], tags: 'nature tropical' },
    'pine tree': { syn: 'pine trees|pines|fir|conifer|evergreen', type: 'plant', tags: 'nature' },
    willow: { syn: 'weeping willow', type: 'plant', look: ['long, trailing curtains of leaves'], tags: 'nature' },
    bonsai: { type: 'plant', look: ['a miniature twisted trunk in a shallow ceramic pot'], tags: 'japan calm' },
    flowers: { plural: 1, syn: 'flower|wildflowers|blooms|florals|bloom|hibiscus|jasmine|frangipani|dahlia|peony|peonies|magnolia', type: 'plant', look: ['soft petals in layered color'], tags: 'nature' },
    rose: { syn: 'roses', type: 'plant', look: ['velvety petals'], tags: 'romance' },
    lotus: { syn: 'lotus flower|water lily|water lilies|lily pads', type: 'plant', look: ['pale petals opening above floating pads'], hab: 'pond:4', tags: 'nature sacred calm' },
    sunflower: { syn: 'sunflowers', type: 'plant', look: ['heavy golden heads turned toward the light'], tags: 'nature summer' },
    tulips: { plural: 1, syn: 'tulip|daffodils|poppies|poppy|daisies|orchids|orchid', type: 'plant', tags: 'nature spring' },
    marigold: { plural: 1, syn: 'marigolds|genda|marigold garlands|garlands|flower garlands', type: 'plant', look: ['strings of saffron and orange blooms'], tags: 'india festive' },
    cactus: { syn: 'cacti|succulent|succulents|saguaro', type: 'plant', hab: 'desert:3', tags: 'desert' },
    mushroom: { syn: 'mushrooms|fungi|toadstool|toadstools', type: 'plant', look: ['tiny caps beaded with moisture'], hab: 'forest:3', tags: 'nature whimsical', bias: { shot: 'macro:2' } },
    moss: { mass: 1, syn: 'ferns|fern|lichen', type: 'plant', tags: 'nature damp' },
    vines: { plural: 1, syn: 'ivy|creepers|vine|overgrowth', type: 'plant', tags: 'nature overgrown' },
    'autumn leaves': { plural: 1, syn: 'fallen leaves|leaves|maple leaves|dry leaves', type: 'plant', look: ['crisp leaves in rust, amber and gold'], tags: 'autumn' },
    bamboo: { mass: 1, syn: 'bamboo stalks', type: 'plant', tags: 'nature asia' },
    grass: { mass: 1, syn: 'tall grass|reeds|wheat', type: 'plant', tags: 'nature' },

    // ---- sky & cosmos ----
    moon: { syn: 'full moon|crescent moon|moonrise|blood moon|harvest moon', type: 'sky', look: ['a luminous disc with softly visible craters'], tags: 'night sky moonlit', bias: { time: 'night:5', key: [['cool silver moonlight washing over everything', 5]] } },
    stars: { plural: 1, syn: 'starry sky|starfield|night sky|star|starlight|constellations', type: 'sky', tags: 'night sky', bias: { time: 'night:6' } },
    'milky way': { syn: 'galaxy|galaxies|nebula|nebulae|cosmos|universe', type: 'sky', look: ['a luminous band of stars and dust'], tags: 'night sky cosmic', bias: { time: 'night:6' } },
    planet: { syn: 'planets|saturn|jupiter|earth|exoplanet|gas giant', type: 'sky', look: ['a vast curved horizon of swirling color'], tags: 'space cosmic' },
    comet: { syn: 'meteor|shooting star|meteor shower|shooting stars|asteroid', type: 'sky', look: ['a bright streak with a glowing tail'], tags: 'sky cosmic', bias: { time: 'night:5' } },
    eclipse: { syn: 'solar eclipse|lunar eclipse', type: 'sky', look: ['a blazing corona around a black disc'], tags: 'sky cosmic' },
    sun: { syn: 'sunburst|sunstar', type: 'sky', look: ['a blazing sunstar'], tags: 'sky day' },
    clouds: { plural: 1, syn: 'cloud|cumulus|cloudscape|cumulonimbus|sea of clouds', type: 'sky', look: ['towering sculpted clouds'], tags: 'sky' },

    // ---- effects & elements ----
    fire: { mass: 1, syn: 'flames|flame|blaze|inferno|bonfire|campfire|burning fire', type: 'fx', light: 'flickering orange firelight', look: ['licking tongues of flame'], tags: 'fire glow' },
    steam: { syn: 'vapor|vapour|steaming', n: 'rising steam', type: 'fx', mass: 1, look: ['soft curls of steam'], tags: 'steam' },
    smoke: { syn: 'smoke plume|plumes of smoke|smoky', mass: 1, type: 'fx', look: ['curling plumes of smoke'], tags: 'smoke' },
    sparks: { plural: 1, syn: 'embers|spark|glowing embers|ash', type: 'fx', look: ['drifting orange embers'], tags: 'fire glow' },
    fireworks: { plural: 1, syn: 'firework|pyrotechnics|crackers|firecrackers', type: 'fx', light: 'bursting fireworks', look: ['blooms of colored light across the sky'], tags: 'festive night glow', bias: { time: 'night:6' } },
    lava: { mass: 1, syn: 'magma|molten rock|lava flow', type: 'fx', light: 'the hellish glow of molten lava', tags: 'fire volcanic glow' },
    explosion: { syn: 'blast|detonation|explosions', type: 'fx', light: 'the blinding flash of an explosion', look: ['a billowing fireball'], tags: 'fire action' },
    splash: { syn: 'water splash|splashes|droplets|water droplets', type: 'fx', look: ['frozen crowns of water droplets'], tags: 'water', bias: { pace: 'slow motion:2' } },
    bubbles: { plural: 1, syn: 'bubble|soap bubbles', type: 'fx', look: ['iridescent floating spheres'], tags: 'playful' },
    procession: { syn: 'parade procession|religious procession|processions', type: 'fx', look: ['a long, surging line of people moving together'], tags: 'crowd festive' },
    confetti: { mass: 1, syn: 'streamers', type: 'fx', look: ['fluttering flecks of bright paper'], tags: 'festive' },
    fireflies: { plural: 1, syn: 'firefly|glowworms|lightning bugs', type: 'fx', light: 'hundreds of drifting fireflies', tags: 'glow magic night', bias: { time: 'night:4, dusk:2' } },
    'sky lanterns': { plural: 1, syn: 'floating lanterns|kongming lanterns|lantern festival', type: 'fx', light: 'hundreds of glowing sky lanterns', tags: 'festive glow night', bias: { time: 'night:5' } },
    petals: { plural: 1, syn: 'flower petals|rose petals|falling petals|petal', type: 'fx', look: ['petals drifting through the air'], tags: 'romance' },
    'colored powder': { mass: 1, syn: 'gulal|color powder|colour powder|abir|holi powder|coloured powder', type: 'fx', look: ['vivid clouds of pink, yellow and green powder'], tags: 'festive india' },
    waves: { plural: 1, syn: 'wave|surf|breakers|crashing waves|big waves', type: 'fx', look: ['curling walls of water with wind-torn spray'], tags: 'water ocean' },
    ice: { mass: 1, syn: 'icicles|ice crystals|frost crystals', type: 'fx', look: ['glassy blue ice'], tags: 'cold' },
    water: { mass: 1, syn: 'puddle|puddles|pond water|running water', type: 'fx', look: ['rippling reflective water'], tags: 'water reflection' },
    reflection: { plural: 1, syn: 'reflections|mirror reflection', type: 'fx', tags: 'reflection' },
    shadows: { plural: 1, syn: 'shadow|long shadows|shadow play', type: 'fx', tags: 'shadow' },
    dust: { mass: 1, syn: 'dust particles|dust motes|sand', type: 'fx', look: ['glittering motes of dust'], tags: 'dust' },
    feathers: { plural: 1, syn: 'feather|floating feathers', type: 'fx', look: ['feathers drifting weightlessly'], tags: 'soft' },
    paper: { syn: 'papers|paper planes|origami', type: 'fx', look: ['creased paper forms'], tags: 'craft' },
    chains: { plural: 1, syn: 'chain|shackles', type: 'fx', tags: 'dark' },
    graffiti: { plural: 1, syn: 'street art|mural|murals', type: 'fx', look: ['layers of vivid spray paint'], tags: 'urban street' },
  });
})();

// ---- garments: "in a red hoodie", "wearing a saree" → wardrobe, never a place ----
(function () {
  const SC = globalThis.SC;
  const G = {};
  ('hoodie jacket coat dress saree sari kurta suit t-shirt tshirt shirt jeans kimono uniform raincoat sweater jumper gown lehenga sherwani dhoti ' +
    'turban hat cap beanie scarf hijab veil tuxedo overalls trench-coat bikini swimsuit pyjamas pajamas robe cloak cape poncho skirt shorts blazer ' +
    'cardigan vest tank-top crop-top tracksuit kaftan abaya burqa salwar anarkali dupatta shawl parka windbreaker apron armour armor spacesuit wetsuit ' +
    'sundress tutu leggings sweatshirt bomber lingerie underwear bra camisole corset bodysuit swimsuit trunks sherwani dhoti mundu qipao hanbok thobe toga tiara').split(' ').forEach((g) => (G[g.replace(/-/g, ' ')] = {}));
  G['leather jacket'] = {}; G['denim jacket'] = {}; G['trench coat'] = {}; G['sari'] = { n: 'saree' }; G['tshirt'] = { n: 't-shirt' };
  G['jeans'] = { plural: 1 }; G['shorts'] = { plural: 1 }; G['pyjamas'] = { plural: 1 }; G['pajamas'] = { plural: 1 }; G['leggings'] = { plural: 1 };
  SC.def('garment', G);
})();
